services:
  - type: web
    name: birducc-backend
    env: java
    plan: free
    buildCommand: cd birducc && ./mvnw clean install
    startCommand: java -jar birducc/target/*.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
