spring.application.name=birducc

# MongoDB Configuration
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=birducc
spring.data.mongodb.uri=mongodb+srv://manuelviverosrealpe:jdvjhYDOlWPW3xHG@cluster0.s6jbwyx.mongodb.net/birducc?retryWrites=true&w=majority


# Server Configuration
server.address=0.0.0.0

# Telegram Configuration
telegram.api.id=8039458211
telegram.bot.token=8039458211:AAFSBTUMvjazFoGNILFepbSYxvwSa7ehHg8
telegram.bot.username=BIRDUCC_bot
telegram.webapp.url=https://0ed9-2800-484-a38b-a200-3118-9219-3ef3-733d.ngrok-free.app

# Frontend Configuration
frontend.url=https://0ed9-2800-484-a38b-a200-3118-9219-3ef3-733d.ngrok-free.app

# Security Configuration
spring.security.user.name=admin
spring.security.user.password=admin

# CORS Configuration
spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=false


